{{- $servicePrefix := .Values.nameOverride | default .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $servicePrefix }}-configmap
data:
  {{- if .Values.config }}
  {{- with .Values.config }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  TZ: Asia/Dhaka
  {{- end }}