{{- $servicePrefix := .Values.nameOverride | default .Release.Name -}}
{{- range .Values.volumes }}
{{- if eq .type "dynamic-pvc" }}
{{- $accessMode := .accessModes | default "ReadWriteOnce" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $servicePrefix }}-{{ .name }}-data
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $servicePrefix }}-app
spec:
  accessModes:
    - {{ $accessMode }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .spec.storageClass }}
{{- end }}
{{- end }}