{{- $servicePrefix := .Values.nameOverride | default .Release.Name -}}
{{- range .Values.service }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $servicePrefix }}-{{ .name }}-service
  {{- with .annotations }}
  labels:
    onechart.kubernetes.io/name: {{ $servicePrefix }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ if eq .type "Headless" }}ClusterIP{{ else }}{{ .type }}{{ end }}
  {{- if eq .type "Headless" }}
  clusterIP: None
  {{- end }}
  selector:
    app: {{ $servicePrefix }}-app
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
{{- end }}